# -*- coding: utf-8 -*-
"""plot_comparison.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tYeqAEtgC8b8iWFDP1alEAoS8PFkmTuf
"""

import matplotlib.pyplot as plt
import csv

# Чтение данных
sizes = []
bubble, insert, shaker, std_sort = [], [], [], []

with open('timing_results.csv', 'r') as f:
    reader = csv.DictReader(f)
    for row in reader:
        sizes.append(int(row['size']))
        bubble.append(float(row['bubble_ms']))
        insert.append(float(row['insert_ms']))
        shaker.append(float(row['shaker_ms']))
        std_sort.append(float(row['std_ms']))

# 1. Логарифмический график (log-log)
plt.figure(figsize=(10, 6))
plt.loglog(sizes, bubble, 'o-', label='Bubble', linewidth=2)
plt.loglog(sizes, insert, 's-', label='Insert', linewidth=2)
plt.loglog(sizes, shaker, '^-', label='Shaker', linewidth=2)
plt.loglog(sizes, std_sort, 'D-', label='std::sort', linewidth=2)

plt.xlabel('Размер массива (n)', fontsize=12)
plt.ylabel('Время (мс)', fontsize=12)
plt.title('Сравнение времени сортировок (логарифмический масштаб)', fontsize=14)
plt.grid(True, which='both', linestyle='--', alpha=0.7)
plt.legend(fontsize=11)
plt.tight_layout()
plt.savefig('sorting_loglog.png', dpi=150)
plt.close()

# 2. Линейный график
plt.figure(figsize=(10, 6))
plt.plot(sizes, bubble, 'o-', label='Bubble', linewidth=2)
plt.plot(sizes, insert, 's-', label='Insert', linewidth=2)
plt.plot(sizes, shaker, '^-', label='Shaker', linewidth=2)
plt.plot(sizes, std_sort, 'D-', label='std::sort', linewidth=2)

plt.xlabel('Размер массива (n)', fontsize=12)
plt.ylabel('Время (мс)', fontsize=12)
plt.title('Сравнение времени сортировок (линейный масштаб)', fontsize=14)
plt.grid(True, linestyle='--', alpha=0.7)
plt.legend(fontsize=11)
plt.tight_layout()
plt.savefig('sorting_linear.png', dpi=150)
plt.close()

