# -*- coding: utf-8 -*-
"""plot_comparison.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tYeqAEtgC8b8iWFDP1alEAoS8PFkmTuf
"""

import matplotlib.pyplot as plt
import csv

# Списки для данных
sizes = []
linear, bst, rbt, hsh, mmap = [], [], [], [], []
collisions = []

# Чтение CSV-файла
with open('search_times.csv', 'r') as f:
    reader = csv.DictReader(f)
    for row in reader:
        sizes.append(int(row['size']))
        linear.append(float(row['linear_ms']))
        bst.append(float(row['bst_ms']))
        rbt.append(float(row['rbt_ms']))
        hsh.append(float(row['hash_ms']))
        mmap.append(float(row['multimap_ms']))
        collisions.append(int(row['collisions']))

# 1. Логарифмический масштаб (log-log)
plt.figure(figsize=(10, 6))
plt.loglog(sizes, linear, 'o-', label='Линейный поиск', linewidth=2)
plt.loglog(sizes, bst, 's-', label='BST (несбаланс.)', linewidth=2)
plt.loglog(sizes, rbt, '^-', label='Красно-чёрное дерево', linewidth=2)
plt.loglog(sizes, hsh, 'D-', label='Хеш-таблица', linewidth=2)
plt.loglog(sizes, mmap, 'v-', label='std::multimap', linewidth=2)

plt.xlabel('Размер массива (N)', fontsize=12)
plt.ylabel('Время поиска (мс)', fontsize=12)
plt.title('Сравнение методов поиска (log-log)', fontsize=14)
plt.grid(True, which='both', linestyle='--', alpha=0.7)
plt.legend(fontsize=11)
plt.tight_layout()
plt.savefig('search_time_loglog.png', dpi=150)
plt.close()

# 2. Линейный масштаб времени
plt.figure(figsize=(10, 6))
plt.plot(sizes, linear, 'o-', label='Линейный поиск', linewidth=2)
plt.plot(sizes, bst, 's-', label='BST (несбаланс.)', linewidth=2)
plt.plot(sizes, rbt, '^-', label='Красно-чёрное дерево', linewidth=2)
plt.plot(sizes, hsh, 'D-', label='Хеш-таблица', linewidth=2)
plt.plot(sizes, mmap, 'v-', label='std::multimap', linewidth=2)

plt.xlabel('Размер массива (N)', fontsize=12)
plt.ylabel('Время поиска (мс)', fontsize=12)
plt.title('Сравнение методов поиска (линейный масштаб)', fontsize=14)
plt.grid(True, linestyle='--', alpha=0.7)
plt.legend(fontsize=11)
plt.tight_layout()
plt.savefig('search_time_linear.png', dpi=150)
plt.close()

# 3. График коллизий (линейный масштаб)
plt.figure(figsize=(10, 6))
plt.plot(sizes, collisions, 'o-', color='darkred', linewidth=2)
plt.xlabel('Размер массива (N)', fontsize=12)
plt.ylabel('Количество коллизий', fontsize=12)
plt.title('Зависимость числа коллизий хеш-таблицы от N', fontsize=14)
plt.grid(True, linestyle='--', alpha=0.7)
plt.tight_layout()
plt.savefig('collisions.png', dpi=150)
plt.close()

print("Графики сохранены: search_time_loglog.png, search_time_linear.png, collisions.png")
plt.show()