# -*- coding: utf-8 -*-
"""pseudorandomplots.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dd1zbBwmj1meQK4R3IRMIZMWQS10MGkd
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

df = pd.read_csv('random_stats.csv')

# Гистограмма χ² по генераторам
plt.figure(figsize=(10, 6))
for gen, color in zip(df['generator'].unique(), ['blue', 'green', 'red']):
    subset = df[df['generator'] == gen]
    plt.hist(subset['chi2'], bins=10, alpha=0.5, label=gen, color=color)
plt.axvline(x=30.1435, color='black', linestyle='--', label='Critical χ² (α=0.05)')
plt.xlabel('Chi-squared statistic')
plt.ylabel('Frequency')
plt.title('Distribution of χ² statistics (20 samples each)')
plt.legend()
plt.tight_layout()
plt.savefig('chi2_hist.png', dpi=150)
plt.close()

# Boxplot коэффициента вариации
plt.figure(figsize=(8, 5))
sns.boxplot(data=df, x='generator', y='cv')
plt.axhline(y=0.57735, color='gray', linestyle='--', label='Theoretical CV (uniform)')
plt.title('Coefficient of variation by generator')
plt.legend()
plt.tight_layout()
plt.savefig('cv_boxplot.png', dpi=150)
plt.close()

# График средних значений с доверительными интервалами
plt.figure(figsize=(8, 5))
for gen, color in zip(df['generator'].unique(), ['blue', 'green', 'red']):
    subset = df[df['generator'] == gen]
    plt.errorbar(gen, subset['mean'].mean(), yerr=subset['mean'].std(), fmt='o', color=color, capsize=5)
plt.axhline(y=4999.5, color='gray', linestyle='--', label='Expected mean (4999.5)')
plt.ylabel('Mean value')
plt.title('Sample means ± std')
plt.legend()
plt.tight_layout()
plt.savefig('mean_comparison.png', dpi=150)
plt.close()

print('Графики сохранены: chi2_hist.png, cv_boxplot.png, mean_comparison.png')

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

df = pd.read_csv('nist_results.csv')

# Переводим в длинный формат для удобства
melted = df.melt(id_vars='generator', var_name='Test', value_name='p_value')

# Boxplot p‑value для каждого теста и генератора
plt.figure(figsize=(12, 6))
sns.boxplot(data=melted, x='Test', y='p_value', hue='generator')
plt.axhline(y=0.01, color='red', linestyle='--', label='Significance level α=0.01')
plt.yscale('log')  # логарифмический масштаб для наглядности
plt.title('NIST test p‑values by generator')
plt.xticks(rotation=45)
plt.legend()
plt.tight_layout()
plt.savefig('nist_boxplot.png', dpi=150)
plt.close()

# Тепловая карта средних p‑value
pivot = df.groupby('generator').mean()  # среднее по каждому тесту
plt.figure(figsize=(8, 4))
sns.heatmap(pivot, annot=True, cmap='RdYlGn', vmin=0, vmax=1, center=0.5)
plt.title('Average p‑values (NIST tests)')
plt.tight_layout()
plt.savefig('nist_heatmap.png', dpi=150)
plt.close()

print('Графики сохранены: nist_boxplot.png, nist_heatmap.png')

df = pd.read_csv('speed_results.csv')
sizes = df['size']
plt.figure(figsize=(10, 6))
plt.loglog(sizes, df['MLCG_ms'], 'o-', label='MLCG')
plt.loglog(sizes, df['Andxorshift_ms'], 's-', label='Andxorshift')
plt.loglog(sizes, df['MXG521_ms'], '^-', label='MXG521')
plt.loglog(sizes, df['StandardRand_ms'], 'D-', label='std::rand')

plt.xlabel('Sample size (N)')
plt.ylabel('Time (ms)')
plt.title('Generation speed comparison')
plt.grid(True, which='both', linestyle='--', alpha=0.7)
plt.legend()
plt.tight_layout()
plt.savefig('speed_comparison.png', dpi=150)
plt.show()